# Generated by Django 5.1.5 on 2025-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="doc_id",
            field=models.CharField(
                blank=True,
                max_length=25,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
