# Generated by Django 5.1.5 on 2025-01-20 10:53

import APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="DoB",
            field=models.DateField(validators=[APP.models.doctor_age]),
        ),
        migrations.AlterField(
            model_name="staff",
            name="DoB",
            field=models.DateField(validators=[APP.models.staff_age]),
        ),
    ]
