# Generated by Django 5.1.5 on 2025-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_alter_doctor_dob_alter_staff_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="types",
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
