# Generated by Django 5.1.5 on 2025-01-20 11:29

import APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0003_payment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="DoA",
            field=models.DateField(validators=[APP.models.past_day]),
        ),
    ]
